// Generated by https://quicktype.io

export interface UserInfo {
    userInfo: UserInfoClass;
}

export interface UserInfoClass {
    userId?: string;
    accountname: string;
    creativity:  number;
    objectives:  string;
    themes:      string;
    userimage:   string;
    username:    string;
}
